{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.name }}
  name: {{ .Values.serviceAccount.name }}
  {{- else }}
  name: {{ include "zenrock.fullname" . }}
  {{- end }}
  labels:
    {{- include "zenrock.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
